[env:esp12f]
platform = espressif8266
; ESP-12F + CH340 载板按 NodeMCU V2 配置（4MB Flash, 80MHz）
board = nodemcuv2
framework = arduino
lib_deps = dancol90/ESP8266Ping
monitor_speed = 115200
; 若烧录不稳，把下面这行改回 115200
upload_speed = 460800
